---
- name: "Check for postfix_exporter binary"
  ansible.builtin.stat:
    path: "{{ postfix_exporter_install_dir }}/postfix-exporter"
  changed_when: false
  register: postfix_exporter_install

- name: "Install tasks"
  when: not postfix_exporter_install.stat.exists or postfix_exporter_force_install|bool
  block:
    - name: "Install requierements"
      ansible.builtin.package:
        name: "ca-certificates"
        state: present

    - name: "Download postfix_exporter..."
      ansible.builtin.get_url:
        url: '{{ postfix_exporter_url }}'
        dest: '{{ postfix_exporter_install_dir }}/postfix-exporter'
        timeout: 60
        mode: '0755'

- name: "Create systemd for postfix_exporter"
  ansible.builtin.template:
    src: 'postfix_exporter.service.j2'
    dest: '/etc/systemd/system/postfix_exporter.service'
    mode: '0644'
  notify: "Restart postfix_exporter"

- name: "Enable and Start postfix_exporter.service"
  ansible.builtin.service:
    name: postfix_exporter
    state: started
    enabled: true
    daemon_reload: true
